--Declarations
const NAMES = {
	FEMININE = {
		"Aisha",
		"Amara",
		"Chloe",
		"Fatima",
		"Freya",
		"Grace",
		"Imogen",
		"Isla",
		"Maya",
		"Mia",
		"Priya",
		"Ruby",
		"Sofia",
		"Zara",
	},
	MASCULINE = {
		"Ben",
		"Daniel",
		"Haris",
		"Jayden",
		"Leo",
		"Lucas",
		"Noah",
		"Oliver",
		"Theo",
	},
	UNISEX = {
		"Alex",
		"Ellis",
		"Jamie",
		"Jordan",
		"Kai",
		"Rowan",
		"Sam",
	},
}
const HAIRS = {
	FEMININE = {
		2956239660,
		451220849,
		376526888,
	},
	MASCULINE = {
		63690008,
		9243992729,
		3814474927,
		376524487,
	},
	UNISEX = {
		9174355709,
		3814476174,
		7193450455,
	},
}
const CLASSIC_SHIRTS = {
	FEMININE = {},
	MASCULINE = {},
	UNISEX = {
		607785314,
		3670737444,
		398633584,
		144076358,
		382538059,
		398635081,
		398634295,
		4047886060,
		144076436,
		382537702,
	},
}
const CLASSIC_PANTS = {
	FEMININE = {},
	MASCULINE = {},
	UNISEX = {
		398633812,
		398635338,
		398634487,
		144076760,
		382538503,
		382537950,
		382537569,
		382537806,
		667684668,
		855780360,
	},
}
const BODY_COLORS = {
	UNISEX = {
		{ 255, 224, 189 },
		{ 241, 194, 125 },
		{ 224, 172, 105 },
		{ 198, 134, 66 },
		{ 141, 85, 36 },
		{ 92, 60, 37 },
	},
}

return {
	NAMES = NAMES,
	HAIRS = HAIRS,
	CLASSIC_SHIRTS = CLASSIC_SHIRTS,
	CLASSIC_PANTS = CLASSIC_PANTS,
	BODY_COLORS = BODY_COLORS,
}
